# Generated by Django 3.1.4 on 2020-12-07 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20201206_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='username',
        ),
        migrations.AddField(
            model_name='content',
            name='username',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
